module.exports = {
  apps: [
    {
      name: 'mbs-deploy-hook',
      script: '/var/app/sands/deploy-hook.js',
      interpreter: 'node',
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'mbs-backend',
      cwd: '/var/app/sands/backend',
      script: 'npm',
      args: 'start',
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
        // Secrets loaded from /var/app/sands/backend/.env via dotenv/config in server.js
      },
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
      error_file: '/var/app/sands/logs/backend-error.log',
      out_file: '/var/app/sands/logs/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'mbs-frontend',
      cwd: '/var/app/sands/frontend',
      script: '/usr/bin/serve',
      args: '-s dist -p 5001 --no-clipboard',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
      },
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
      error_file: '/var/app/sands/logs/frontend-error.log',
      out_file: '/var/app/sands/logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'mbs-admin',
      cwd: '/var/app/sands/admin',
      script: '/usr/bin/serve',
      args: '-s dist -p 5002 --no-clipboard',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
      },
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
      error_file: '/var/app/sands/logs/admin-error.log',
      out_file: '/var/app/sands/logs/admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
