module.exports = {
  apps: [
    {
      name: 'mbs-backend',
      cwd: '/var/app/sands/backend',
      script: 'npm',
      args: 'start',
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
        DB_HOST: '127.0.0.1',
        DB_PORT: 3306,
        DB_USER: 'mbs_app',
        DB_PASSWORD: 'Noname@2022',
        DB_NAME: 'mbays_game',
      },
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'mbs-frontend',
      cwd: '/var/app/sands/frontend',
      script: '/usr/bin/serve',
      args: '-s dist -p 5001',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
      },
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'mbs-admin',
      cwd: '/var/app/sands/admin',
      script: '/usr/bin/serve',
      args: '-s dist -p 5002',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
      },
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
    },
  ],
};
